### ISSUE TITLE
worktile的看板与github的commit关联起来

### ISSUE THREAD

**Issue by zhysora** [sebuaa2019/Team109#1]
自己完善自己的任务描述，附上commit code
![屏幕快照 2019-05-21 下午3 20 16](https://user-images.githubusercontent.com/30565507/58076137-0a756c80-7bdc-11e9-8b49-4f2588e77b92.png)
![屏幕快照 2019-05-21 下午3 20 31](https://user-images.githubusercontent.com/30565507/58076139-0d705d00-7bdc-11e9-8278-2fd179b4a21e.png)

**Comment by zhysora** [comment]
或者有什么别的更好的建议也可以提

**Comment by Clinale** [comment]
好，没问题

**Comment by ffiamz** [comment]
除了新任务，以前的任务尽量也添加一下。如果依次commit完成了两种任务的话就都写一下，不过最好还是写一些push一些

**Comment by jy0205** [comment]
好的，已经将push记录和看板正常关联
