### ISSUE TITLE
Log与实时信息显示

### ISSUE THREAD

**Issue by ffiamz** [sebuaa2019/Team109#11]
Log的信息是多久更新依次数据库啊。如果Log会进入数据库的话，就不需要写文件了，我通过AJAX和数据库的检索就能显示扫地等的实时信息了。（写文件似乎会对机器人代码运行产生一些不太好的影响的样子）这样需要扫地通过ROS_INFO以一个固定格式输出（其实就三个数挨个输出就好了）

**Comment by ffiamz** [comment]
我想问下往数据库里写东西怎么保证不重复的。 @waveliu98

**Comment by waveliu98** [comment]
logs在存入数据库时会执行get_or_create的方法，可以自动去除重复信息
关于刷新问题，每次刷新前端网页就可以重新执行一次读取rosout.log的操作

**Comment by jy0205** [comment]
你们关于日志的存放还是利用数据库吧
