### ISSUE TITLE
大launch 来了DAZE✨！！

### ISSUE THREAD

**Issue by zhysora** [sebuaa2019/Team109#12]
### 启动launch
```
roslaunch core_109 core_109.launch
```
将各个模块的依赖背景结点都融进了core_109/core_109.launch中，理论上其他模块再运行的时候只需要rosrun自己的核心node，欢迎大家测试自己的模块，有问题bug请及时反馈
### 关闭launch
```
rosnode kill rviz
``` 
rviz在launch中设为了required，所有想要关闭所有的依赖背景，只需kill掉rviz即可，亲测可行。别的模块关闭自己的功能，也只需要rosnode kill [node_name]即可

**Comment by zhysora** [comment]
目前发现的一个问题：
由于mapsever和gmapping是一同开启的，所以建图完成后为了让mapsever加载最新的map，需要整个launch重启一遍。这个可能需要依赖于用户操作，即建完图保存后需要重启一下机器人

**Comment by jy0205** [comment]
还有，一定要把rosrun my_map_package control_pub.py这条指令加进去，这是我们遥控机器人的指令

**Comment by zhysora** [comment]
这个要放在这个大launch里面吗，我觉得这个是单独的模块运行的

**Comment by ffiamz** [comment]
这个东西就跑着就可以，毕竟不按按键它就不会起作用，这样就省得每次按开始了

**Comment by ffiamz** [comment]
@zhysora 新launch启动以后机器人在rviz界面上剧烈抖动，你有啥头绪吗

**Comment by ffiamz** [comment]
而且王闯的东西好像不能用

**Comment by zhysora** [comment]
秘制抖动好像是机器人无法准确知道自己的位置

**Comment by zhysora** [comment]
如果用原来的launch不会有这种情况的话那就说明全部合在一起开还是负担太大了

**Comment by zhysora** [comment]
那就不如还是用原来的分开launch的方法，反正现在知道如何kill node和launch了，可以通过require来实现

**Comment by zhysora** [comment]
分散为各个launch, 可用rviz kill
```
roslaunch clean_module my_clean.launch [mode:=] [level:=]
roslaunch grab_109 grab_obj.launch [templpath:=]
roslaunch my_map_package move_control.launch 
```
