### ISSUE TITLE
合并之后的问题

### ISSUE THREAD

**Issue by zhysora** [sebuaa2019/Team109#14]
机器人的log出现了些问题，dfs_clean中的ROS_INFO全部没有输出，导致面积、距离、时间的统计收到了影响。扫地与抓取都有一定不稳定差异

**Comment by ffiamz** [comment]
dfs_clean的信息已经调试解决。
log界面已修改。
不稳定问题问题可能处在电脑和机器上。尤其抓取受光线影响
