### ISSUE TITLE
关于单元测试

### ISSUE THREAD

**Issue by zhysora** [sebuaa2019/Team109#2]
我觉得就是把代码逻辑的一小部分提取出来，单独写个测试代码即可，可以参考我clean_module/src下的几个test_前缀的code

**Comment by Clinale** [comment]
那我稍后参考一下，然后把抓取模块的测试文件上传上来

**Comment by jy0205** [comment]
我会对网页的响应逻辑做一些测试，检查后端的功能

**Comment by ffiamz** [comment]
网页的部分总结成txt，里面把所有要测的点列出来。其它的不方便代码测的也可以这么写。

**Comment by waveliu98** [comment]
稍后我也传一下

**Comment by ffiamz** [comment]
大家测试文件的路径有时间都发一下吧，在这里汇总一下，到时候好找

**Comment by waveliu98** [comment]
https://github.com/sebuaa2019/Team109/blob/master/RobotSrc/unit_test/log_test/views.py
