### ISSUE TITLE
关于launch文件

### ISSUE THREAD

**Issue by zhysora** [sebuaa2019/Team109#3]
大家机器人用到的.lanch文件都往这发下吧，方便合并

**Comment by Clinale** [comment]
这是启动抓取模块所需要的launch文件
https://github.com/sebuaa2019/Team109/blob/master/RobotSrc/grab_109/launch/grab_obj.launch

**Comment by zhysora** [comment]
感谢

**Comment by jy0205** [comment]
这是建图模块所需要的launch文件，https://github.com/sebuaa2019/Team109/blob/master/RobotSrc/mapping_109/launch/my_gmapping.launch
另外，因为我需要重新编写运动控制模块的代码，等我写好后，会给你那部分的launch

**Comment by zhysora** [comment]
好的
