### ISSUE TITLE
launch指令

### ISSUE THREAD

**Issue by ffiamz** [sebuaa2019/Team109#4]
方便网页使用，roslaunch和rosrun指令的标准格式发到这里吧

**Comment by zhysora** [comment]
扫地模块：
roslaunch clean_module my_clean.launch
rosrun clean_module dfs_clean [mode] [level]
后续合并launch后就最后一句话够了

**Comment by jy0205** [comment]
建图模块的启动是不是已经包含在扫地里面了？

**Comment by ffiamz** [comment]
现在launch还没合并完，先发自己的，周环宇合好了再发合在一起的

**Comment by jy0205** [comment]
roslaunch my_map_package my_gmapping.launch

**Comment by zhysora** [comment]
还在合

**Comment by Clinale** [comment]
roslaunch grab_109 grab_obj.launch

**Comment by Clinale** [comment]
这个是启动物体抓取的launch文件

**Comment by ffiamz** [comment]
@wc411421  你增加了自定义标签后把新的命令行发一下

**Comment by Clinale** [comment]
rosrun grab_109 grab_obj  _templpath:=标签路径

**Comment by zhysora** [comment]
大launch没戏 了， 各自的launch我看了下，都是可以用rosnode kill rviz关闭的

**Comment by Clinale** [comment]
那开启抓取服务时，需要两步：
1、roslaunch grab_109 grab_obj.launch
2、rosrun grab_109 grab_109 {_templpath:=/home/robot/catkin_ws/src/grab_109/src/label/default.jpg}
其中，括号中的为可选项，用于设置标签路径，如果没有，启动默认标签
