### ISSUE TITLE
关于实现对机器人控制的讨论

### ISSUE THREAD

**Issue by jy0205** [sebuaa2019/Team109#6]
目前，我遇到的问题是：我使用文件传入的交互方式，网页中点击按钮，向文件中写入相应的控制信息，然后使用那个键盘控制机器人的node去读取，已经可以获取到相应的指令，并且该node也已经发布了vel_cmd主题，但是机器人就是不动，你们有什么见解吗？

**Comment by jy0205** [comment]
很玄学的一个bug

**Comment by jy0205** [comment]
备用的解决方式是，写一个可以一直让机器人动的node，然后我们每次手动kill(点击相应的按钮)。但是上次，不能kill掉，我怀疑是使用os.system造成的阻塞问题。

**Comment by ffiamz** [comment]
可以试下通过文件或者别的之类的交互

**Comment by jy0205** [comment]
已经解决了
