### ISSUE TITLE
标签征集

### ISSUE THREAD

**Issue by Clinale** [sebuaa2019/Team109#7]
现面向小组征集新标签。
标签特征如下：
1、纹理不要太多
2、最好不要单一纯色
3、最好不要和常见颜色冲突
4、最多三个纯色

多多益善。

**Comment by ffiamz** [comment]
![1](https://user-images.githubusercontent.com/36148533/58327610-9d273d00-7e62-11e9-9463-7147633d4ded.jpg)
![2](https://user-images.githubusercontent.com/36148533/58327622-a0bac400-7e62-11e9-872d-cf7eae705b36.jpg)
![3](https://user-images.githubusercontent.com/36148533/58327625-a31d1e00-7e62-11e9-9f98-70fe1ca3d7ac.jpg)
![4](https://user-images.githubusercontent.com/36148533/58327631-a44e4b00-7e62-11e9-99ce-4ec9d50527e6.jpg)
我用画图画了几个（这个不难弄吧
