### ISSUE TITLE
关于界面上的多余内容

### ISSUE THREAD

**Issue by ffiamz** [sebuaa2019/Team109#8]
目前网页上有一些可能没有用的元素：contact，两个search，信箱和铃铛状的图标。这些都是借鉴的模板图标，那些需要留下，那些需要删除呢

**Comment by jy0205** [comment]
contact和里面的那个search去掉，其它的我会加内容

**Comment by jy0205** [comment]
这些你先不用管啊，先把扫地页面，还有导航弄好啊
